package(default_visibility = ["//visibility:public"])

java_binary(
    name = "cup_bin",
    main_class = "java_cup.Main",
    runtime_deps = ["//cup/cup"],
)

alias(
    name = "cup",
    actual = "//cup/cup"
)
