package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # GPL-compatible

java_import(
    name = "cup",
    jars = ["cup/target/cup-11b.jar"],
)

alias(
    name = "cup_runtime",
    actual = "//cup/cup_runtime",
)
