package(default_visibility = ["//jflex:visibility"])

java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/com/google/guava",
    ],
    testonly = True,
)
