java_test(
    name = "HexaUtilsTest",
    srcs = ["HexaUtilsTest.java"],
    deps = [
        "//java/jflex/testing/assertion",
        "//java/jflex/ucd_generator/util:hexa_utils",
        "//third_party/com/google/truth",
    ],
)
