java_library(
    name = "jflex",
    srcs = glob(["*.java"]),
    deps = [
        "//jflex",
        "@jsr305//jar",
        "//third_party/com/google/guava",
        "//third_party/org/apache/maven:maven_plugin_api",
    ],
    visibility = ["//jflex-maven-plugin/src/test:__subpackages__"],
)
