java_test(
    name = "BazelFileUtilTest",
    srcs = ["java/jflex/common/testing/BazelFileUtilTest.java"],
    deps = [
        "//third_party/com/google/truth",
        "//jflex/common-testing/src/main/java/jflex/common/testing",
    ],
    data=[
        "java/jflex/common/testing/a.txt",
        "data/b.txt",
    ]
)

java_test(
    name = "BazelUtilTest",
    srcs = ["java/jflex/common/testing/BazelUtilTest.java"],
    deps = [
        "//third_party/com/google/truth",
        "//jflex/common-testing/src/main/java/jflex/common/testing",
    ],
)
