java_library(
    name = "unicode",
    srcs = glob(["**/*.java"]),
    visibility = ["//jflex:__subpackages__"],
    deps = [
        "//jflex/java/jflex/exception",
        "//jflex/java/jflex/unicode/data:unicode_data",
    ],
)
