# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0

buildtools_cache:
  folder: buildtools

container:
  image: l.gcr.io/google/bazel:2.1.0
  memory: 5G

bazel_build__test_task:
  name: Bazel build and test
  bazel_version_script:
  - bazel --bazelrc=.ci.bazelrc info  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  release
  build_script:
  - bazel --bazelrc=.ci.bazelrc build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //jflex
  build_all_script:
  - bazel --bazelrc=.ci.bazelrc build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //...
  test_script:
  - bazel --bazelrc=.ci.bazelrc test  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //jflex/...
  regression_tests_script:
  - bazel --bazelrc=.ci.bazelrc test  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //javatests/jflex/testcase/...
  test_all_script:
  - bazel --bazelrc=.ci.bazelrc test  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //...
  always:
    junit_artifacts:
      path: "bazel-out/*/testlogs/**/test.xml"
      type: text/xml
      format: junit

bazel_artifact_task:
  name: Bazel artifact
  build_artifact_script:
  - bazel --bazelrc=.ci.bazelrc build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  jflex/jflex_bin_deploy.jar
  binary_artifacts:
    path: "bazel-out/*/bin/jflex/jflex_bin_deploy.jar"
    type: application/java-archive

measure_coverage_task:
  name: Measure code coverage
  measure_coverage_script:
  - bazel --bazelrc=.ci.bazelrc coverage --combined_report=none --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //javatests/... //jflex/...
  send_coverage_report_script:
  - scripts/send-code-coverage.sh
  only_if: $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BRANCH == 'cirrus'
  environment:
    CODACY_PROJECT_TOKEN: ENCRYPTED[2fac1c4b7834a7f75477aa710279eaaa65db5999d9d0219940eb1e9679a38073c9fd99f240904ab318f95aab5eea5af9]

codestyle_task:
  name: Check code style
  container:
    image: openjdk:8-jdk
  check_java_format_script: scripts/test-java-format.sh
  check_bzl_format_script:  scripts/test-bzl-format.sh

steps:
- restore_cache:
  keys:
  - source-v1-{{ .Branch }}-{{ .Revision }}
  - source-v1-{{ .Branch }}-
  - source-v1--
- checkout
- git_cache:
  key: source-v1-{{ .Branch }}-{{ .Revision }}
  paths:
  - ".git"
