# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0


build_task:
  name: Bazel build and test
  container:
    image: cirrusci/bazel:latest
  check_script:
  - bazel --bazelrc=.ci.bazelrc info  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  release
  build_script:
  - bazel --bazelrc=.ci.bazelrc build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //jflex
  build_all_script:
  - bazel --bazelrc=.ci.bazelrc build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //...
  test_script:
  - bazel --bazelrc=.ci.bazelrc test  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //jflex/...
  regression_tests_script:
  - bazel --bazelrc=.ci.bazelrc test  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //testsuite/...
  test_all_script:
  - bazel --bazelrc=.ci.bazelrc test  --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //...
codestyle_task:
  name: Check code style
  container:
    image: openjdk:8-jdk
  script: scripts/test-java-format.sh

