#!/bin/bash

# build all projects and run tests

# fail on error
set -e

# builds and tests main projects
mvn install test

# regression test suite must run from its own directory
cd testsuite/testcases && mvn test

# also check ant build
cd ../../jflex && ant gettools build

## run jflex examples:

# don't assume byacc/j is installed, just run lexer
cd examples/byaccj && make Yylex.java
cd ../cup && make
cd ../interpreter && make
cd ../java && make
cd ../simple-maven && mvn test
cd ../standalone-maven && mvn test
cd ../zero-reader && make
