java_library(
  name = "hello",
  srcs = ["Hello.java"],
  javacopts = ["-source","7","-target","7"],
)

java_binary(
  name = "Hello",
  runtime_deps = [
    ":hello",
  ],
  javacopts = ["-source","7","-target","7"],
)
