package(default_visibility = ["//jflex:visibility"])

java_library(
    name = "scanner",
    srcs = glob(["*.java"]),
    visibility = ["//jflex:visibility"],
    deps = [
        "//jflex/src/main/java/jflex/l10n",
    ],
)
