java_test(
    name = "UnicodeDataScannerTest",
    srcs = ["UnicodeDataScannerTest.java"],
    data = ["//third_party/unicode:ucd_10"],
    deps = [
        "//java/jflex/ucd_generator/scanner:unicode_data",
        "//java/jflex/ucd_generator/scanner:unicode_scanners",
        "//java/jflex/ucd_generator/ucd",
        "//third_party/com/google/guava",
        "//third_party/com/google/truth",
    ],
)
