java_test(
    name = "JavaPackageUtilsTest",
    srcs = ["JavaPackageUtilsTest.java"],
    deps = [
        "//java/jflex/util/javac:package_util",
        "//third_party/com/google/truth",
    ],
)
