load("//testsuite:testsuite.bzl", "jflex_testsuite")

jflex_testsuite(
    name = "NoUnusedTest",
    srcs = [
        "NoUnusedTest.java",
    ],
    data = [
        "expected_sysout.txt",
        "no-unused.flex",
    ],
    deps = [
    ],
)
