java_test(
    name = "SkeletonTest",
    srcs = ["SkeletonTest.java"],
    data = [
        "//jflex:resources",
    ],
    deps = [
        "//jflex:testing",
        "//jflex/src/main/java/jflex/skeleton",
        "//third_party/com/google/truth",
    ],
)
