load("//testsuite:testsuite.bzl", "jflex_testsuite")

jflex_testsuite(
    name = "DiffOutputStreamTest",
    srcs = ["DiffOutputStreamTest.java"],
    deps = [
        "//testsuite/bzltestsuite/java/jflex/testing/assertion",
        "//testsuite/bzltestsuite/java/jflex/testing/diff",
    ],
)
