package(default_visibility = ["//testsuite:__subpackages__"])

java_library(
    name = "diff",
    srcs = ["DiffOutputStream.java"],
    deps = [
        "//third_party/com/google/truth",
        "//third_party/junit",
    ],
)
