java_test(
    name = "YylexTest",
    srcs = ["java/YylexTest.java"],
    data = [
        "data/output.good",
        "data/test.txt",
    ],
    deps = [
        "//jflex/examples/simple",
        "//third_party/com/google/truth",
        "//jflex/common-testing/src/main/java/jflex/common/testing"
    ],
)
