java_test(
    name = "YylexTest",
    srcs = ["java/YylexTest.java"],
    data = [
        "data/output.good",
        "data/test.txt",
    ],
    deps = [
        "//simple",
        "//third_party/com/google/truth",
    ],
)
