java_test(
    name = "EmitterTest",
    srcs = ["EmitterTest.java"],
    data = [
        "UnicodeProperties.java.golden",
    ],
    deps = [
        "//java/jflex/testing/diff",
        "//java/jflex/testing/javac",
        "//java/jflex/ucd_generator",
        "//java/jflex/ucd_generator/ucd",
        "//third_party/com/google/truth",
    ],
)

