java_test(
    name = "EmitterTest",
    srcs = ["EmitterTest.java"],
    deps = [
        "//java/jflex/testing/diff",
        "//java/jflex/testing/javac",
        "//java/jflex/ucd_generator",
        "//third_party/com/google/truth",
    ],
    data = [
        "//jflex/src/main/java/jflex/core:unicode/UnicodeProperties.java"
    ]
)
