java_test(
    name = "UcdVersionsTest",
    srcs = ["UcdVersionsTest.java"],
    deps = [
        "//java/jflex/ucd_generator/ucd",
        "//third_party/com/google/truth",
    ],
)

java_test(
    name = "VersionTest",
    srcs = ["VersionTest.java"],
    deps = [
        "//java/jflex/ucd_generator/ucd",
        "//third_party/com/google/truth",
    ],
)
