package(default_visibility = ["//jflex:visibility"])

java_library(
    name = "generator",
    srcs = glob(["*.java"]),
    deps = [
        "//jflex/src/main/java/jflex/base",
        "//jflex/src/main/java/jflex/core",
        "//jflex/src/main/java/jflex/exceptions",
        "//jflex/src/main/java/jflex/io",
        "//jflex/src/main/java/jflex/l10n",
        "//jflex/src/main/java/jflex/performance",
    ],
)
