#
# For your own project, please see https://github.com/jflex-de/bazel_rules
#
# This is only to test that the examples build with the SNAPSHOT version of JFLex.
#

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "jflex_bazel_rules",
    remote = "https://github.com/jflex-de/bazel_rules.git",
    tag = "stable",
)

load("//third_party:generate_workspace.bzl", "generated_maven_jars")

generated_maven_jars()
