# Workspace file for the Bazel build system
# https://bazel.build/

# JFlex doesn't use Bazel itself, but some examples do.
# This WORKSPACE is only to illustrate usage of Bazel on the examples.
# In a real usage, the WORKSPACE file is at the root of the workspace.
# https://docs.bazel.build/versions/master/build-ref.html#workspace

# TODO(#390) Add maven 1.7.0 when cup_runtime is published
# de.jflex:jflex-maven-plugin:maven-plugin:1.6.1
native.maven_jar(
    name = "de_jflex_jflex_1_6_1",
    artifact = "de.jflex:jflex:1.6.1",
    # TODO() Use jcenter.bintray.com when synced with central
    repository = "https://jcenter.bintray.com/",
    sha1 = "eb4d51e1a8ea7ee96068905ddeceb9b28737c7eb",
)
