package(default_visibility = ["//jflex:visibility"])

java_library(
    name = "anttask",
    srcs = glob(["*.java"]),
    deps = [
        "//jflex",
        "//third_party/org/apache/ant",
    ],
)
