package(default_visibility = ["//jflex:visibility"])

java_library(
    name = "anttask",
    srcs = glob(["*.java"]),
    deps = [
        "//jflex/src/main/java/jflex/exceptions",
        "//jflex/src/main/java/jflex/generator",
        "//third_party/org/apache/ant",
    ],
)
