java_test(
    name = "ApiPrivateTest",
    srcs = ["ApiPrivateTest.java"],
    data = [
        "AttemptPrivateAccess.java",
        "private.flex",
    ],
    deps = [
        "//testsuite/bzltestsuite",
        "//testsuite/bzltestsuite/java/jflex/testing/annotations",
        "//testsuite/bzltestsuite/java/jflex/testing/javac",
        "//third_party/com/google/guava",
        "//third_party/com/google/truth",
    ],
)
