java_test(
    name = "ApiPrivateTest",
    srcs = ["ApiPrivateTest.java"],
    data = ["private.flex", "AttemptPrivateAccess.java"],
    deps = [
        "//testsuite/bzltestsuite",
        "//third_party/com/google/guava",
        "//third_party/com/google/truth",
    ],
)
