package(default_visibility = ["//jflex:visibility"])

java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    deps = [
        "//jflex",
        "//jflex/src/main/java/jflex/exceptions",
        "//jflex/src/main/java/jflex/l10n",
    ],
)
