load("//testsuite:testsuite.bzl", "jflex_testsuite")

jflex_testsuite(
    name = "MacroComplementTest",
    srcs = [
        "MacroComplementTest.java",
    ],
    data = [
        "macro.flex",
    ],
    deps = [
        "//jflex/src/main/java/jflex/exceptions",
        "//third_party/com/google/guava",
    ],
)
