package(default_visibility = ["//testsuite:__subpackages__"])

java_library(
    name = "bzltestsuite",
    exports = [
        "//testsuite/bzltestsuite/java/jflex/testing/annotations",
        "//testsuite/bzltestsuite/java/jflex/testing",
    ],
)

alias(
    name = "javac",
    actual = "//testsuite/bzltestsuite/java/jflex/testing/javac",
)