java_library(
    name = "bzltestsuite",
    srcs = glob(["java/**/*.java"]),
    visibility = ["//testsuite/javatests:__subpackages__"],
    deps = [
        "//jflex",
        "//third_party/com/google/guava",
        "//third_party/junit",
    ],
)
