java_library(
    name = "unicode",
    srcs = glob(["data/*.java"]) + [
        "IntCharSet.java",
        "UnicodeProperties.java",
    ],
    visibility = ["//jflex:__subpackages__"],
    deps = [
        "//jflex/src/main/java/jflex/chars",
        "//jflex/src/main/java/jflex/logging",
    ],
)
