%%

%unicode 9.0
%public
%class UnicodeScripts_9_0

%type int
%standalone

%include ../../resources/common-unicode-all-enumerated-property-java

%%

<<EOF>> { printOutput(); return 1; }
\p{Adlam} { setCurCharPropertyValue("Adlam"); }
\p{Ahom} { setCurCharPropertyValue("Ahom"); }
\p{Anatolian_Hieroglyphs} { setCurCharPropertyValue("Anatolian_Hieroglyphs"); }
\p{Arabic} { setCurCharPropertyValue("Arabic"); }
\p{Armenian} { setCurCharPropertyValue("Armenian"); }
\p{Avestan} { setCurCharPropertyValue("Avestan"); }
\p{Balinese} { setCurCharPropertyValue("Balinese"); }
\p{Bamum} { setCurCharPropertyValue("Bamum"); }
\p{Bassa_Vah} { setCurCharPropertyValue("Bassa_Vah"); }
\p{Batak} { setCurCharPropertyValue("Batak"); }
\p{Bengali} { setCurCharPropertyValue("Bengali"); }
\p{Bhaiksuki} { setCurCharPropertyValue("Bhaiksuki"); }
\p{Bopomofo} { setCurCharPropertyValue("Bopomofo"); }
\p{Brahmi} { setCurCharPropertyValue("Brahmi"); }
\p{Braille} { setCurCharPropertyValue("Braille"); }
\p{Buginese} { setCurCharPropertyValue("Buginese"); }
\p{Buhid} { setCurCharPropertyValue("Buhid"); }
\p{Canadian_Aboriginal} { setCurCharPropertyValue("Canadian_Aboriginal"); }
\p{Carian} { setCurCharPropertyValue("Carian"); }
\p{Caucasian_Albanian} { setCurCharPropertyValue("Caucasian_Albanian"); }
\p{Chakma} { setCurCharPropertyValue("Chakma"); }
\p{Cham} { setCurCharPropertyValue("Cham"); }
\p{Cherokee} { setCurCharPropertyValue("Cherokee"); }
\p{Common} { setCurCharPropertyValue("Common"); }
\p{Coptic} { setCurCharPropertyValue("Coptic"); }
\p{Cuneiform} { setCurCharPropertyValue("Cuneiform"); }
\p{Cypriot} { setCurCharPropertyValue("Cypriot"); }
\p{Cyrillic} { setCurCharPropertyValue("Cyrillic"); }
\p{Deseret} { setCurCharPropertyValue("Deseret"); }
\p{Devanagari} { setCurCharPropertyValue("Devanagari"); }
\p{Duployan} { setCurCharPropertyValue("Duployan"); }
\p{Egyptian_Hieroglyphs} { setCurCharPropertyValue("Egyptian_Hieroglyphs"); }
\p{Elbasan} { setCurCharPropertyValue("Elbasan"); }
\p{Ethiopic} { setCurCharPropertyValue("Ethiopic"); }
\p{Georgian} { setCurCharPropertyValue("Georgian"); }
\p{Glagolitic} { setCurCharPropertyValue("Glagolitic"); }
\p{Gothic} { setCurCharPropertyValue("Gothic"); }
\p{Grantha} { setCurCharPropertyValue("Grantha"); }
\p{Greek} { setCurCharPropertyValue("Greek"); }
\p{Gujarati} { setCurCharPropertyValue("Gujarati"); }
\p{Gurmukhi} { setCurCharPropertyValue("Gurmukhi"); }
\p{Han} { setCurCharPropertyValue("Han"); }
\p{Hangul} { setCurCharPropertyValue("Hangul"); }
\p{Hanunoo} { setCurCharPropertyValue("Hanunoo"); }
\p{Hatran} { setCurCharPropertyValue("Hatran"); }
\p{Hebrew} { setCurCharPropertyValue("Hebrew"); }
\p{Hiragana} { setCurCharPropertyValue("Hiragana"); }
\p{Imperial_Aramaic} { setCurCharPropertyValue("Imperial_Aramaic"); }
\p{Inherited} { setCurCharPropertyValue("Inherited"); }
\p{Inscriptional_Pahlavi} { setCurCharPropertyValue("Inscriptional_Pahlavi"); }
\p{Inscriptional_Parthian} { setCurCharPropertyValue("Inscriptional_Parthian"); }
\p{Javanese} { setCurCharPropertyValue("Javanese"); }
\p{Kaithi} { setCurCharPropertyValue("Kaithi"); }
\p{Kannada} { setCurCharPropertyValue("Kannada"); }
\p{Katakana} { setCurCharPropertyValue("Katakana"); }
\p{Kayah_Li} { setCurCharPropertyValue("Kayah_Li"); }
\p{Kharoshthi} { setCurCharPropertyValue("Kharoshthi"); }
\p{Khmer} { setCurCharPropertyValue("Khmer"); }
\p{Khojki} { setCurCharPropertyValue("Khojki"); }
\p{Khudawadi} { setCurCharPropertyValue("Khudawadi"); }
\p{Lao} { setCurCharPropertyValue("Lao"); }
\p{Latin} { setCurCharPropertyValue("Latin"); }
\p{Lepcha} { setCurCharPropertyValue("Lepcha"); }
\p{Limbu} { setCurCharPropertyValue("Limbu"); }
\p{Linear_A} { setCurCharPropertyValue("Linear_A"); }
\p{Linear_B} { setCurCharPropertyValue("Linear_B"); }
\p{Lisu} { setCurCharPropertyValue("Lisu"); }
\p{Lycian} { setCurCharPropertyValue("Lycian"); }
\p{Lydian} { setCurCharPropertyValue("Lydian"); }
\p{Mahajani} { setCurCharPropertyValue("Mahajani"); }
\p{Malayalam} { setCurCharPropertyValue("Malayalam"); }
\p{Mandaic} { setCurCharPropertyValue("Mandaic"); }
\p{Manichaean} { setCurCharPropertyValue("Manichaean"); }
\p{Marchen} { setCurCharPropertyValue("Marchen"); }
\p{Meetei_Mayek} { setCurCharPropertyValue("Meetei_Mayek"); }
\p{Mende_Kikakui} { setCurCharPropertyValue("Mende_Kikakui"); }
\p{Meroitic_Cursive} { setCurCharPropertyValue("Meroitic_Cursive"); }
\p{Meroitic_Hieroglyphs} { setCurCharPropertyValue("Meroitic_Hieroglyphs"); }
\p{Miao} { setCurCharPropertyValue("Miao"); }
\p{Modi} { setCurCharPropertyValue("Modi"); }
\p{Mongolian} { setCurCharPropertyValue("Mongolian"); }
\p{Mro} { setCurCharPropertyValue("Mro"); }
\p{Multani} { setCurCharPropertyValue("Multani"); }
\p{Myanmar} { setCurCharPropertyValue("Myanmar"); }
\p{Nabataean} { setCurCharPropertyValue("Nabataean"); }
\p{New_Tai_Lue} { setCurCharPropertyValue("New_Tai_Lue"); }
\p{Newa} { setCurCharPropertyValue("Newa"); }
\p{Nko} { setCurCharPropertyValue("Nko"); }
\p{Ogham} { setCurCharPropertyValue("Ogham"); }
\p{Ol_Chiki} { setCurCharPropertyValue("Ol_Chiki"); }
\p{Old_Hungarian} { setCurCharPropertyValue("Old_Hungarian"); }
\p{Old_Italic} { setCurCharPropertyValue("Old_Italic"); }
\p{Old_North_Arabian} { setCurCharPropertyValue("Old_North_Arabian"); }
\p{Old_Permic} { setCurCharPropertyValue("Old_Permic"); }
\p{Old_Persian} { setCurCharPropertyValue("Old_Persian"); }
\p{Old_South_Arabian} { setCurCharPropertyValue("Old_South_Arabian"); }
\p{Old_Turkic} { setCurCharPropertyValue("Old_Turkic"); }
\p{Oriya} { setCurCharPropertyValue("Oriya"); }
\p{Osage} { setCurCharPropertyValue("Osage"); }
\p{Osmanya} { setCurCharPropertyValue("Osmanya"); }
\p{Pahawh_Hmong} { setCurCharPropertyValue("Pahawh_Hmong"); }
\p{Palmyrene} { setCurCharPropertyValue("Palmyrene"); }
\p{Pau_Cin_Hau} { setCurCharPropertyValue("Pau_Cin_Hau"); }
\p{Phags_Pa} { setCurCharPropertyValue("Phags_Pa"); }
\p{Phoenician} { setCurCharPropertyValue("Phoenician"); }
\p{Psalter_Pahlavi} { setCurCharPropertyValue("Psalter_Pahlavi"); }
\p{Rejang} { setCurCharPropertyValue("Rejang"); }
\p{Runic} { setCurCharPropertyValue("Runic"); }
\p{Samaritan} { setCurCharPropertyValue("Samaritan"); }
\p{Saurashtra} { setCurCharPropertyValue("Saurashtra"); }
\p{Sharada} { setCurCharPropertyValue("Sharada"); }
\p{Shavian} { setCurCharPropertyValue("Shavian"); }
\p{Siddham} { setCurCharPropertyValue("Siddham"); }
\p{SignWriting} { setCurCharPropertyValue("SignWriting"); }
\p{Sinhala} { setCurCharPropertyValue("Sinhala"); }
\p{Sora_Sompeng} { setCurCharPropertyValue("Sora_Sompeng"); }
\p{Sundanese} { setCurCharPropertyValue("Sundanese"); }
\p{Syloti_Nagri} { setCurCharPropertyValue("Syloti_Nagri"); }
\p{Syriac} { setCurCharPropertyValue("Syriac"); }
\p{Tagalog} { setCurCharPropertyValue("Tagalog"); }
\p{Tagbanwa} { setCurCharPropertyValue("Tagbanwa"); }
\p{Tai_Le} { setCurCharPropertyValue("Tai_Le"); }
\p{Tai_Tham} { setCurCharPropertyValue("Tai_Tham"); }
\p{Tai_Viet} { setCurCharPropertyValue("Tai_Viet"); }
\p{Takri} { setCurCharPropertyValue("Takri"); }
\p{Tamil} { setCurCharPropertyValue("Tamil"); }
\p{Tangut} { setCurCharPropertyValue("Tangut"); }
\p{Telugu} { setCurCharPropertyValue("Telugu"); }
\p{Thaana} { setCurCharPropertyValue("Thaana"); }
\p{Thai} { setCurCharPropertyValue("Thai"); }
\p{Tibetan} { setCurCharPropertyValue("Tibetan"); }
\p{Tifinagh} { setCurCharPropertyValue("Tifinagh"); }
\p{Tirhuta} { setCurCharPropertyValue("Tirhuta"); }
\p{Ugaritic} { setCurCharPropertyValue("Ugaritic"); }
\p{Unknown} { setCurCharPropertyValue("Unknown"); }
\p{Vai} { setCurCharPropertyValue("Vai"); }
\p{Warang_Citi} { setCurCharPropertyValue("Warang_Citi"); }
\p{Yi} { setCurCharPropertyValue("Yi"); }
