java_test(
    name = "ClassInfoTest",
    srcs = ["ClassInfoTest.java"],
    deps = [
        "//jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex",
        "//third_party/com/google/truth",
    ],
)

java_test(
    name = "JFlexMojoTest",
    srcs = ["JFlexMojoTest.java"],
    deps = [
        "//jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex",
        "//third_party/com/google/guava",
        "//third_party/com/google/truth",
        "@org_apache_maven_plugin_testing_maven_plugin_testing_harness//jar",
    ],
)

java_test(
    name = "LexSimpleAnalyzerTest",
    srcs = ["LexSimpleAnalyzerTest.java"],
    deps = [
        "//jflex-maven-plugin/src/main/java/jflex/maven/plugin/jflex",
        "//third_party/com/google/truth",
    ],
)
