java_test(
    name = "RegExpTest",
    srcs = ["RegExpTest.java"],
    deps = [
        "//jflex/src/main/java/jflex/chars",
        "//jflex/src/main/java/jflex/core",
        "//jflex/src/main/java/jflex/core/unicode",
        "//third_party/com/google/truth",
    ],
)

java_test(
    name = "SkeletonTest",
    srcs = ["SkeletonTest.java"],
    data = [
        "//jflex:resources",
    ],
    deps = [
        "//jflex:testing",
        "//jflex/src/main/java/jflex/core",
        "//third_party/com/google/truth",
    ],
)
