package(default_visibility = ["//visibility:public"])

# cli, gui, and ant task
java_library(
    name = "jflex_ui",
    srcs = ["Main.java"], # cli
    deps = [
        "//jflex/src/main/java/jflex/anttask",
        "//jflex/src/main/java/jflex/core",
        "//jflex/src/main/java/jflex/gui",
    ],
)
