/*
 * Copyright (C) 2013 Steve Rowe <sarowe@gmail.com>
 * Copyright (C) 2021 Google, LLC.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
package de.jflex.testcase.unicode.unicode_2_0;

import de.jflex.testing.unicodedata.AbstractEnumeratedPropertyDefinedScanner;
%%
// Generated byUnicodeAgeGenerator from java/de/jflex/migration/unicodedatatest/UnicodeAge.flex.vm

%unicode 2.0
%public
%class UnicodeAge_2_0_age_1_1
%extends AbstractEnumeratedPropertyDefinedScanner

%type int

%init{
  super(65533);
%init}

%%

<<EOF>>     { return YYEOF;}
\p{Age:1.1} { setCurCharPropertyValue(yytext(), yylength(), "Age:1.1"); }
[^] { }
