/*
 * Copyright (C) 2013 Steve Rowe <sarowe@gmail.com>
 * Copyright (C) 2021 Google, LLC.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
package de.jflex.testcase.unicode.unicode_2_0;

import de.jflex.testing.unicodedata.AbstractEnumeratedPropertyDefinedScanner;
%%
// This flex spec was generated by UnicodeAgeGenerator
// from java/de/jflex/migration/unicodedatatest/UnicodeAgeSubtraction.flex.vm

%unicode 2.0
%public
%class UnicodeAge_2_0_age_subtraction
%extends AbstractEnumeratedPropertyDefinedScanner

%type int

%init{
  super(65533);
%init}

%%

<<EOF>>                    { return YYEOF; }
[\p{Age:2.0}--\p{Age:1.1}] {
  setCurCharPropertyValue(yytext(), yylength(), "[\\p{Age:2.0}--\\p{Age:1.1}]");
}
[^] { }
