licenses(["notice"])  # BSD-like
java_library(
    name = "cup_runtime",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility=["//visibility:public"],
    javacopts=[
        # Not our code, there is nothing we can do
        "-XepDisableAllChecks"],
)