java_test(
    name = "AntTaskTests",
    srcs = ["AntTaskTests.java"],
    data = [
        "//jflex/src/main/jflex:skeleton.nested",
        "//jflex/src/test:test_resources",
    ],
    deps = [
        "//jflex",
    ],
)
