java_test(
    name = "AntTaskTests",
    srcs = ["AntTaskTests.java"],
    data = [
        "//jflex/lex:skeleton.nested",
        "//jflex/javatests:test_resources",
    ],
    deps = [
        "//jflex",
    ],
)
