java_library(
    name = "chars",
    testonly = True,
    srcs = ["IntervalGen.java"],
    visibility = ["//jflex:visibility"],
    deps = [
        "//jflex/src/main/java/jflex/chars",
        "//jflex/src/main/java/jflex/core/unicode",
        "//third_party/com/pholser/quickcheck",
    ],
)
