java_test(
    name = "TemplateVarsTest",
    srcs = ["TemplateVarsTest.java"],
    deps = [
        "//java/jflex/testing/assertion",
        "//java/velocity",
        "//third_party/com/google/truth",
        "//third_party/org/apache/velocity",
    ],
)
