java_test(
    name = "IntCharSetTest",
    srcs = ["IntCharSetTest.java"],
    deps = [
        "//jflex/src/main/java/jflex/unicode",
    ],
)

java_test(
    name = "UnicodePropertiesTest",
    srcs = ["UnicodePropertiesTest.java"],
    deps = [
        "//jflex/src/main/java/jflex/unicode",
    ],
)
