java_test(
    name = "UnicodePropertiesTest",
    srcs = ["UnicodePropertiesTest.java"],
    deps = [
        "//jflex/src/main/java/jflex/chars",
        "//jflex/src/main/java/jflex/core",
    ],
)
