package(default_visibility = ["//visibility:public"])

java_library(
    name = "assertion",
    testonly = True,
    srcs = [
        "MoreAsserts.java",
        "ThrowingRunnable.java",
    ],
    deps = [
        "@jsr305//jar",
    ],
)
