package(default_visibility = ["//visibility:public"])

java_library(
    name = "assertion",
    testonly = True,
    srcs = [
        "MoreAsserts.java",
        "ThrowingRunnable.java",
    ],
    deps = [
        "//third_party/com/google/code/findbugs:jsr305",
    ],
)
