load("//testsuite:testsuite.bzl", "jflex_testsuite")

jflex_testsuite(
    name = "BolTest",
    srcs = ["BolTest.java"],
    data = [
        "bol.flex",
    ],
    deps = ["//jflex/src/main/java/jflex/exceptions"],
)

