java_test(
    name = "ActionPipeTest",
    srcs = ["ActionPipeTest.java"],
    deps = [
        "//testsuite/bzltestsuite",
        "//jflex",
    ],
    data = [
        "action-pipe.flex",
    ],
)
