load("//testsuite:testsuite.bzl", "jflex_testsuite")

jflex_testsuite(
    name = "ActionPipeTest",
    srcs = ["ActionPipeTest.java"],
    data = [
        "action-pipe.flex",
    ],
    deps = ["//jflex/src/main/java/jflex/exceptions"],
)
