java_library(
    name = "velocity",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/org/apache/velocity",
    ],
    visibility = [
        "//java/ucd_generator:__subpackages__",
    ],
)
