java_library(
    name = "ucd",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/com/google/guava",
    ],
    visibility = [
        "//java/jflex/ucd_generator:__subpackages__",
        "//javatests/jflex/ucd_generator:__subpackages__",
    ],
)