package(default_visibility = ["//java/jflex/ucd_generator:__subpackages__"])

java_library(
    name = "hexa_utils",
    srcs = ["HexaUtils.java"],
    deps = [
        "//third_party/com/google/guava",
    ],
    visibility = ["//visibility:public"],
)
